# Generated by Django 6.0.6 on 2026-06-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('KIOSK_DEVICE', 'Kiosk Device')], default='TEACHER', max_length=15),
        ),
    ]
