# Generated by Django 6.0.6 on 2026-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceencoding',
            name='angle',
            field=models.CharField(choices=[('front', 'Frontal'), ('left', 'Left profile'), ('right', 'Right profile'), ('up', 'Slightly up'), ('down', 'Slightly down'), ('tilt', 'Slight tilt')], max_length=10),
        ),
    ]
